# Generated by Django 4.0.3 on 2022-06-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=3)),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Emergency Doctor', 'Emergency Doctor'), ('Surgeon', 'Surgeon'), ('ICU Doctor', 'ICU Doctor')], default='Cardiologist', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
