# Generated by Django 4.0.3 on 2022-06-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Emergency ', 'Emergency '), ('Surgery', 'Surgery'), ('ICU', 'ICU '), ('Radiology', 'Radiology')], default='Cardiologist', max_length=50),
        ),
    ]
