# Generated by Django 4.0.3 on 2022-06-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_patient_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Emergency Doctor', 'Emergency Doctor'), ('Surgeon', 'Surgeon'), ('ICU Doctor', 'ICU Doctor'), ('Radiologist', 'Radiologist')], default='Cardiology', max_length=50)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
