# Generated by Django 4.0.3 on 2022-06-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_doctor_department_alter_patient_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
    ]
