# Generated by Django 4.0.3 on 2022-06-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_appointemnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointemnt',
            name='status',
        ),
    ]
