# Generated by Django 4.0.3 on 2022-06-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_rename_appointemnt_appointemnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointemnet',
            new_name='Appointment',
        ),
    ]
