# Generated by Django 4.0.3 on 2022-06-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='status',
            new_name='approve',
        ),
    ]
