# Generated by Django 4.0.3 on 2022-06-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_rename_status_appointment_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointdata',
            field=models.BooleanField(default=False),
        ),
    ]
